### ISSUE TITLE
Variable identifier conflicts with javascript reserved keyword

### ISSUE THREAD

**Issue by xxgreg** [markdown-it/mdurl#1]
I've been using the commonmark.js library which depends on this library. Unfortunately the google closure compiler is unable to parse this library as there is a variable called "char" which is a reserved keyword.

https://github.com/xxgreg/mdurl/commit/5e69d117fc1e48cfe690f525b8b5a71784919a35

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Future_reserved_keywords

**Comment by puzrin** [comment]
Will fix, thanks for report

**Comment by puzrin** [comment]
Fixed

**Comment by xxgreg** [comment]
Cheers ;)
