### ISSUE TITLE
URI support

### ISSUE THREAD

**Issue by christianbundy** [markdown-it/mdurl#2]
Hello!

This module has been working great for me, but we're working with non-URLs like `mailto:`, `magnet:`, and `dat:` where the URI path is being parsed as a host. You can find more information in https://github.com/ssbc/ssb-markdown/issues/25, but would it be possible to support non-URL URIs in this module?

Thanks!

**Comment by puzrin** [comment]
This module supports all valid schemas. I you think opposite - please provide a minimal code sample to prove.

If you have problems with markdown - check markdown's link validator first, it's very restrictive for security reasons.

**Comment by christianbundy** [comment]
Thanks for the quick response!

![800px-uri_syntax_diagram](https://user-images.githubusercontent.com/537700/49170105-46480d00-f2f0-11e8-83b8-429da70fd631.png)

```js
const mdurl = require('mdurl')
console.log(mdurl.parse('scheme:path'))
/* => Url {
  protocol: 'scheme:',
  slashes: null,
  auth: null,
  port: null,
  hostname: 'path',
  hash: null,
  search: null,
  pathname: null }
*/
```

As you can see, the path is being incorrectly parsed as the host.

**Comment by christianbundy** [comment]
It looks like this problem also happens with minimal URNs like `urn:sha1`, but doesn't affect data URIs like `data:,` because they have a comma. Another useful example might be `urn:sha1:YNCKHTQCWBTRNJIV4WNAE52SJUQCZO5C`, where `sha1` is parsed as a hostname:

```js
{
  protocol: 'urn:',
  slashes: null,
  auth: null,
  port: null,
  hostname: 'sha1',
  hash: null,
  search: null,
  pathname: ':YNCKHTQCWBTRNJIV4WNAE52SJUQCZO5C'
}
```

**Comment by puzrin** [comment]
Did you compared behaviour with native `require('url')`? This one was forked for very specific reasons:

- keep tailing `/` somewhere
- crash-less encode/decode

Everything else should be the same, and there are no plans to diverge.

**Comment by christianbundy** [comment]
Thanks for the recommendation. I can confirm that the problem exists with `require('url')`, which is Node's [legacy API](https://nodejs.org/api/url.html#url_url_strings_and_url_objects), but that the bug is resolved when using `new URL` rather than `url.parse()`.

Would you be open to upgrading away from the legacy API to bring this up-to-date?

**Comment by christianbundy** [comment]
Alternatively, would it be better to upgrade markdown-it to use the non-legacy API instead? My goal is to fix this bug but I'm not sure which option would be best. Thanks for your help!

**Comment by puzrin** [comment]
I'd prefer to keep things without changes if possible.
